# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false

addons:
  apt:
    packages:
       # Requirements for NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 
    - python-tk
    - python-tornado
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev
    - cython


language: python

python: 
  - "2.7"
  # - "3.6"  see below
  #- "3.7"
  
# remove this for py3..?
virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate
    # - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=PyNEURON:7.4
    - OMV_ENGINE=PyNEURON:7.5
    - OMV_ENGINE=PyNEURON:7.6
    - OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=PyNN_Brian1

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation    
    - pip install numpy scipy # Why is this needed? Scipy doesn't seem to get installed correctly on trusty with addons above...
    - pip install tables # Ditto
    - pip install matplotlib>=2.2.5 # This is more because Matplotlib v2.x is required...
    - pip install future pandas matplotlib-scalebar bokeh  # For NetPyNE

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests, return code" $OMV_SUCCESS

    - if [[ ${OMV_ENGINE} == "jNeuroML" || ${OMV_ENGINE} == "jNeuroML_NEURON" ]]; then echo "Continuing with test after jNeuroML/jNeuroML_NEURON is run..."; else exit $OMV_SUCCESS; fi
    - echo "Running more tests..."
    - omv list -V 
    - cd NeuroML2
    - ls -alt
    - python spikes.py ${OMV_ENGINE}
    - python spikesFast.py ${OMV_ENGINE}
    - exit $OMV_SUCCESS # in case it failed above...

