# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: trusty
sudo: false 

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-tk
    - python-sympy
    - python-tables 
    - python-tornado
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev
    - cython
    
language: python

python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate
    # - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=PyNEURON:7.4
    - OMV_ENGINE=PyNEURON:7.5
    - OMV_ENGINE=PyNEURON:7.6
    - OMV_ENGINE=PyNN_NEURON
    - OMV_ENGINE=PyNN_Nest
    - OMV_ENGINE=PyNN_Brian1

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests, return code" $OMV_SUCCESS

    - if [[ ${OMV_ENGINE} == "jNeuroML" || ${OMV_ENGINE} == "jNeuroML_NEURON" ]]; then echo "Continuing with test after jNeuroML/jNeuroML_NEURON is run..."; else exit $OMV_SUCCESS; fi
    - echo "Running more tests..."
    - cd NeuroML2
    - ls -alt
    - python spikes.py ${OMV_ENGINE}
    - exit $OMV_SUCCESS # in case it failed above...

